instana/instana-agent-operator

src/main/resources/instana-agent.daemonset.yaml
Ensure instana-agent.daemonset.yaml is on-par with https://github.com/instana/docs/blob/master/src/pages/quick_start/agent_setup/container/kubernetes/assets/instana-agent.yaml where appropriate:
- Use the `apps/v1` API for DaemonSet instead of the deprecated `extensions/v1beta1`
- `DaemonSet` spec selectors must match the pod template's labels: https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.14/#daemonsetspec-v1-apps, therefore adding a matching selector under `spec`
- Use `serviceAccountName` instead of the deprecated `serviceAccount`: https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.14/#podspec-v1-core
- Add mount and volume for `/var/lib/containers/storage`. This was added for CRI-O support.
- Rename the `INSTANA_AGENT_POD_IP` env variable in the …
=> Ensure instana-agent.daemonset.yaml is on-par with the agent daemonset in docs where applicable

deploy/instana-agent.customresource.yaml, docs/install-manually.md, src/main/java/com/instana/operator/AgentDeployer.java, src/main/java/com/instana/operator/customresource/InstanaAgentSpec.java, src/main/resources/instana-agent.daemonset.yaml, src/test/java/com/instana/operator/AgentDeployerTest.java, src/test/java/com/instana/operator/customresource/InstanaAgentSpecDeserializeTest.java, src/test/resources/customresource-max.yaml
We changed the liveness checks in the other configurations (helm, yaml) and also introduced the ability to define arbitrary environment variables in the helm chart.
- Bring the liveness checks in line with the other configurations
- Expose the ability to set arbitrary environment variables via the custom resource. This makes a lot of the values in the Custom Resource redundant as all they do is set an environment variable on the agent - we shouldn't need to maintain this here.
- Remove default `INSTANA_AGENT_HTTP_LISTEN=*` since this is not the default for other configurations.
- Add a test for the `AgentDeployer#newDaemonSet` method which (at this point) only checks the new environment variable logic.
- Update `customresource-max.yaml` with possible values of some environment variables, …
=> Liveness Checks and expose Environment Variables

README.md, docs/configuration.md, docs/install-manually.md, olm/Dockerfile, src/main/java/com/instana/operator/AgentDeployer.java, src/main/java/com/instana/operator/customresource/InstanaAgentSpec.java, src/test/java/com/instana/operator/AgentDeployerTest.java, src/test/java/com/instana/operator/customresource/InstanaAgentSpecDeserializeTest.java, src/test/resources/customresource-max.yaml
Some of our partners require that the image the operator deploys is parameterizable.
This adds the ability to specify the agent image via the `agent.image` parameter in the Instana Agent custom resource.
This also improves the documentation around the parameters which are available for the operator.
=> Parameterize Image

deploy/instana-agent-operator.yaml, src/main/java/com/instana/operator/AgentDeployer.java, src/main/java/com/instana/operator/CustomResourceWatcher.java, src/main/java/com/instana/operator/OperatorLeaderElector.java, src/main/java/com/instana/operator/OperatorPodLoader.java, src/main/java/com/instana/operator/OperatorPodValidator.java, src/main/java/com/instana/operator/client/ClientConfigProducer.java, src/main/java/com/instana/operator/client/KubernetesClientProducer.java, src/main/java/com/instana/operator/customresource/InstanaAgentSpec.java, src/main/java/com/instana/operator/env/Environment.java, src/main/java/com/instana/operator/env/EnvironmentProducer.java, src/main/java/com/instana/operator/env/NamespaceProducer.java, src/main/java/com/instana/operator/env/OperatorPodNameProducer.java, src/test/java/com/instana/operator/AgentDeployerTest.java, src/test/java/com/instana/operator/customresource/InstanaAgentSpecDeserializeTest.java
Operator Lifecycle Manager requires the `RELATED_IMAGE_` environment variable to parameterize the operator image.
This adds that as well as improving testability of Environment variables within the operator codebase by introducing an Environment class which wraps `System.getenv`. This allows injection of the environment variables for testing.
=> Parameterize agent image via RELATED_IMAGE_INSTANA_AGENT env var

Jenkinsfile, olm/create-artifacts.sh, olm/operator-resources/create-github-release.sh, olm/operator-resources/create-operator-artifacts.sh
Changeset includes:
- Only publish to docker for full releases
- Don't version the instana-agent-operator.yaml filename. Instead place it in a versioned directory. This is so that we can use the 'latest' GitHub Release url to link to that file such that the url never changes when new versions are released
=> Allow for an unchanging 'latest' version of the instana-agent-operator.yaml to be published

src/main/resources/instana-agent.clusterrole.yaml
They are added to the operator permissions, but unfortunately we need to add them to two places in the operator
1) for the operator to get the permissions, so it can grant them to the agent
2) for the agent itself
We should consider generating these permissions as well at some point.
=> Add StatefulSet, DaemonSet, CronJobs to agent permissions

olm/operator-resources/operator-artifacts.jsonnet
This breaks doing `kubectl apply` to upgrade
The error I get is
```
The Deployment "instana-agent-operator" is invalid: spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"app.kubernetes.io/name":"instana-agent-operator", "app.kubernetes.io/version":"0.3.1"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable
```
I don't think the version should be in the label selectors because since this field is immutable, one would need to delete the deployment and recreate it when upgrading. The only reason the version _would_ need to be in the label selector is if we were supporting running multiple versions at once, which we do not need to support.
=> Remove version from deployment label selector

olm/operator-resources/instana-agent-operator.yaml, pom.xml, src/main/java/com/instana/operator/AgentDeployer.java, src/main/resources/instana-agent.clusterrole.yaml, src/main/resources/instana-agent.clusterrolebinding.yaml, src/main/resources/instana-agent.configmap.yaml, src/main/resources/instana-agent.daemonset.yaml, src/main/resources/instana-agent.secret.yaml, src/main/resources/instana-agent.serviceaccount.yaml, src/test/java/com/instana/operator/AgentDeployerTest.java
As part of the hand-off of the K8s artifacts to Team Agent, one of the things we want to understand better is how our customers are installing the Instana Agent on their Kubernetes clusters.
Agents installed by Helm similarly have `app.kubernetes.io/managed-by` and `app.kubernetes.io/version` labels on the Kubernetes resources that get created (specifically the DaemonSet). We want to use these labels to build telemetry data to better understand how our customers are installing the agent.
- Add `app.kubernetes.io/managed-by` and `app.kubernetes.io/version` labels to the Agent resources to help identify how the Agent is installed. The `app.kubernetes.io/managed-by` label can be added in the specific resource's YAML, but the `app.kubernetes.io/version` label has to be added dynamically from …
=> Add labels to the Agent resources to help identify how the Agent is installed

.gitignore, Jenkinsfile, olm/operator-resources/create-github-release.sh, olm/operator-resources/download-github-release-assets.sh
RedHat has recently changed the process for updating a new version of the operator. One of the last steps of this process was to upload the operator bundle, which includes some metadata and manifests in the form of yaml files. This used to be a manual process by which we would upload a zip file at this location: https://connect.redhat.com/project/3928601/operator-metadata. However, there is now an Operator Bundle project https://connect.redhat.com/project/5791371/images, where you can upload a docker container image containing the same files. Therefore, we should perform this last step automatically instead of having to remember to do this manually.
Update the Jenkins pipeline to download all the assets for a specific GitHub Release (so as to not assume that those assets are available on …
=> Upload RedHat Operator bundle automatically for full release tags

Jenkinsfile, README.md, docs/build.md, docs/testing-with-kind.md, e2e-testing/with-kind/create-cluster.sh, e2e-testing/with-kind/delete-cluster.sh, e2e-testing/with-kind/kind-config-darwin.yaml, e2e-testing/with-kind/kind-config-linux.yaml, olm/operator-resources/instana-agent-operator.yaml, olm/operator-resources/operator-artifacts.jsonnet, olm/template.jsonnet, pom.xml, src/main/java/com/instana/operator/AgentDeployer.java, src/main/java/com/instana/operator/CustomResourceState.java, src/main/java/com/instana/operator/CustomResourceWatcher.java, src/main/java/com/instana/operator/cache/Cache.java, src/main/java/com/instana/operator/cache/ListerWatcher.java, src/main/java/com/instana/operator/client/KubernetesClientProducer.java, src/test/java/com/instana/operator/AgentDeployerTest.java
The version of the `quarkus` dependency is sorely outdated (`1.2.1.Final`). In order for us to leverage the `v1` api of `CustomResourceDefinition` (which we will need to do soon since `v1beta1/CustomResourceDefinition` is deprecated and will be removed in Kubernetes v1.22+), we need at least `kubernetes-client 4.11.x`. Version `1.9.0.Final` of quarkus gives us `kubernetes-client 4.12`. The last version update of `kubernetes-client` Quarkus did was to `4.10.3` before that.
**Note**: This is a breaking change as the version of `kubernetes-client` that's used when calling `.createOrReplace` on the Custom Resource's status requires an additional `create` permission in the ClusterRole for `instana.io`.
- The main change here is the version bump of quarkus from 1.2.1.Final to 1.9.0.Final and …
=> [Breaking change] Upgrade quarkus from 1.2.1.Final to 1.9.0.Final

.circleci/config.yml, .githooks/pre-commit, docs/build.md, e2e-testing/with-kind/create-cluster.sh, pom.xml
Similar to https://github.com/instana/backend/pull/8634
We added license headers to all relevant source files in #47. However, running `mvn validate license:format` needs to be somewhat automated for new files being checked in going forward so that engineers don't have to remember to run it manually.
In the near future, we could have a single entrypoint script like `./go` or `Makefile` (which delegates to `mvn` or other tools) that can manage all the sequencing of steps and which ones are required so we don't have to rely on specific tooling like Maven plugins for such things.
Added a pre-commit git hook in `.githooks/` that runs `mvn validate license:format` and configure it to be run automatically by using [git-build-hook-maven-plugin](https://github.com/rudikershaw/git-build-hook). …
=> Pre-commit git hook that ensures the required license headers are added where appropriate

src/main/java/com/instana/operator/cache/ResourceMap.java, src/test/java/com/instana/operator/cache/CacheTest.java
When setting watches, the client receives Resource Versions to know if something got updated.
Currently this version is converted to an `int` and doing a 'greater than' comparison to learn if the new version is newer.
But according to Kubernetes doc, the String value can't be converted to integer and should just be compared as-is to learn if changes happened. See: https://kubernetes.io/docs/reference/using-api/api-concepts/#resource-versions
So making that change in the code, to just process String values.
=> Fix Resource Version parsing, as String instead of numeric

.dockerignore, Jenkinsfile, buildspec.yml, ci/pipeline.yaml, src/main/docker/Dockerfile.codebuild
This new [Concourse CI pipeline](https://ci.instana.io/teams/agent/pipelines/agent-operator-release) 
* builds the current Java based operator from release tags (`v1.0.7`) and pre-release tags (`v1.0.8-pre` or `v1.0.8-<your-name-here>`)
* builds multi-architecture docker images (amd64, arm64, s390x) on AWS CloudBuild
* publishes internal to GCR
* for release tags: publishes to docker.io (multi-arch) & Red Hat Container Registry (only amd64, [details here](https://access.redhat.com/solutions/5583611))
* builds the OLM bundle
* builds OLM docker images and publishes internal to GCR
* for release tags: publishes OLM to Red Hat Container Registry
=> Build multi-arch images on Concourse CI

licenses/LICENSE
Changing license to Apache 2.0 and be aligned with [instana-agent-docker](https://github.com/instana/instana-agent-docker).
=> Change from Expat to Apache 2.0 license

ci/pipeline.yaml
This PR adds Power (ppc64le) support to the Concourse CI pipeline. Test build: [plinux-agent-operator](https://ci.instana.io/teams/agent/pipelines/plinux-agent-operator)
- adds ppc64le to the list of ARCHs handled by multi-architecture build/publish via Concourse CI.
The image pushed by the CI to GCR has been validated on ppc64le by making sure that the pod comes up properly on minikube cluster. Logs below.
```
NAMESPACE       NAME                                      READY   STATUS             RESTARTS   AGE
instana-agent   instana-agent-operator-6b596f8d67-2qk4n   1/1     Running            0          12s
kube-system     coredns-f9fd979d6-rjvm8                   1/1     Running            1          52d
kube-system     etcd-p006vm71                             1/1     Running …
```
=> Enable P support in Concourse CI

bundle/manifests/instana-agent-operator.clusterserviceversion.yaml
See https://access.redhat.com/documentation/en-us/openshift_container_platform/4.7/html-single/operators/index
OLM places the CSV in the failed phase if a conversion webhook definition does not adhere to the following constraints:
CSVs featuring a conversion webhook can only support the AllNamespaces install mode.
=> Only AllNamespaces is allowed for conversion webhook definitions

go.mod, go.sum
Signed-off-by: ZachRobinson <zachrobinson@ibm.com>
=> update containerd version to patch out CVE-2021-43816

controllers/leaderelection/coordination_api/http_client.go
"io/ioutil" has been deprecated since Go 1.16: As of Go 1.16, the same functionality is now provided by package io
=> Use io package instead of ioutil package

config/samples/instana_v1_extended_instanaagent.yaml
Public Cloud Providers use serviceAccount annotations to enable pod identity.
- [Story / Card](https://instana.kanbanize.com/ctrl_board/50/cards/156768/details/)
=> Add serviceAccount annotations

Dockerfile
Without including pkg folder build errors are thrown, example:
```
0.636 api/v1/inline_types.go:15:2: no required module provides package github.com/instana/instana-agent-operator/pkg/map_defaulter; to add it:
0.636   go get github.com/instana/instana-agent-operator/pkg/map_defaulter
...
```
Comparing against main shows that the pkg folder was added as part of the operator_3.0 branch and is required in order to build the container image.
The target `make docker-build` works after the change.
Also, the MAINTAINER label is deprecated and should be replaced by using the standardized label `org.opencontainers.image.authors`: https://docs.docker.com/reference/dockerfile/#maintainer
=> ci(fix): Fix docker build for Golang 1.22.1

.dockerignore, Makefile, bundle/manifests/instana-agent-operator.clusterserviceversion.yaml, bundle/manifests/instana.io_agents.yaml, config/manager/kustomization.yaml
- By default, the images are build and pushed with the `latest` tag. This can cause accidental overwrites of the `latest` tag, if not used with care. As additional safeguard, the default is changed to `snapshot` to avoid interfering with production images.
The final product build can just export the image name to overwrite it to the right location. After changing the tag, I recreated bundle files.
- The .dockerignore file worked for docker-engine before, but podman failed to find the pkg folder if not explicitly listed as found by @Milica-Cvrkota-IBM
=> chore: Change default image tag, adjust .dockerignore

Makefile, bundle/manifests/instana-agent-operator.clusterserviceversion.yaml, config/rbac/role.yaml, controllers/instanaagent_controller.go
The ClusterRole produced by the kubebuilder comments when running `make manifests` was out of sync with the definition in the CustomResourceDefinition. 
Whenever the operator was started locally via `make run`, the permissions from the local kubeconfig were inherited and worked fine, but starting from an image inside the cluster which relied on the serviceaccount mapped to the manger-role ClusterRole failed with forbidden.
This can be reproduced by running: `kubectl get
--as=system:serviceaccount:instana-agent:instana-agent-operator instanaagent.instana.io/instana-agent -n instana-agent`
Also worth noting: There is a custom verb `bind` for `rbac.authorization.k8s.io`. It must be set in this context, otherwise the operator is not allowed to bind a `clusterrole` to a `serviceaccount`, even …
=> fix: Adjust kubebuilder to fix cluster role

go.mod
Invalid format of go version causes .mod related go commands to exit 2
```
invalid -go=go1.22.1
exit status 2
```
=> Fix issue where go exits due to go version being the wrong format

config/manager/manager.yaml
Card reference: [159440](https://instana.kanbanize.com/ctrl_board/50/cards/159440/details/)
If the name of the operator deployment is `instana-agent-operator`, the initial install works fine. It still becomes a problem, once we try to update existing operator v2 installations, as the `instana-agent-operator` pods will try to become leader and conflict with existing `manager-controller` pods.
By adjusting the name of the deployment, Kubernetes will apply a rolling-update to the operator deployment and thereby will demote existing leaders and let new deployments win the leader election eventually.
On a GKE cluster, the v2 installation looks like below by default (with a custom resource instance deployed):
```
$ kubectl get all -n instana-agent
NAME                                     READY …
```
=> fix: Adjust operator deployment name for backwards compatibility 

go.mod
Build pipeline is currently failing with
```
go: download go1.22 for linux/amd64: toolchain not available
```
The issue and fix is outlined: https://github.com/golang/go/issues/62278
=> Specify patch of the toolchain to fix pipeline

ci/pipeline.yaml
- ((branch)) is undefined on main, it only works for instanced pipelines.
- Remove trigger for pipeline-source on tag-release, as otherwise two tags are created for the same commit
=> ci(fixup): Apply fixes for the main pipeline

Makefile, ci/pipeline.yaml
Before publishing a release, it should be checked if the operator image is really present in the target registry
=> ci(fixup): Enable image promotion, add sanity check

config/samples/instana_v1_extended_instanaagent.yaml
Previously the cpu request were by default at 1% of a CPU. This meant that in every deployment the CPU usage was always more than the minimum CPU resource scheduled.
The memory limit which is the maximum before the process is killed with an OOM is increased to 2GB to be conservative with clusters with many updates and resources, where memory usage usually hovers around 1.3G
=> instana_v1_extended_instanaagent: increase cpu requests and memory limits of k8sensor

ci/pipeline.yaml, ci/pr-pipeline.yml
The used OCP cluster is currently in a broken state. While we create a new cluster, this should not block pipelines
=> ci: Temporary disable broken OCP cluster

config/manager/manager.yaml
Allow up to 600Mi memory consumption, even if only 200Mi get requested upfront. Only the leader pod might exceed the 200Mi and the real amount of memory might depend on the environment, therefore adding some buffer.
See https://github.com/instana/instana-agent-operator/issues/170 and TS016461105
=> chore: Increase memory limit of controller manager

config/manager/manager.yaml
Allow up to 600Mi memory consumption, even if only 200Mi get requested upfront. Only the leader pod might exceed the 200Mi and the real amount of memory might depend on the environment, therefore adding some buffer.
=> chore: Increase memory limit of controller manager (#171)

ci/RELEASE.md
In case the CI promotion fails, document how to create PRs manually.
Should be safe to merge, I placed the markdown in the ci folder which will not trigger a new release automatically.
=> doc(ci): Describe manual operator catalog promotion

pkg/k8s/object/builders/common/volume/volume.go, pkg/k8s/object/builders/common/volume/volume_test.go
This change helps to avoid deployment failures on systems where these directories are not pre-created.
`instana-agent   8s          Warning   Failed              pod/instana-agent-lsrf9                       Error: Error response from daemon: invalid mount config for type "bind": bind source path does not exist: /var/vcap/sys/run/containerd`
[Agent charts PR](https://github.ibm.com/instana/instana-agent-charts/pull/114)
=> Add type: DirectoryOrCreate to DaemonSet definitions to ensure required directories exist

api/v1/inline_types.go, api/v1/inline_types_test.go, config/samples/instana_v1_extended_instanaagent.yaml
This PR enables OTLP by default within the Operator
- [Story / Card](https://jsw.ibm.com/browse/INSTA-8047)
- [Chart PR](https://github.ibm.com/instana/instana-agent-charts/pull/118)
=> Enable OTLP by default

ci/scripts/cleanup-resources.sh, ci/scripts/end-to-end-test.sh
The check for the CR state "Running" seem to be flaky.
When having a look into it more closely, it appears that the operator deployment from the feature branch could be that slow, that the old operator is still running while continuing the test.
This change will enforce that the operator deployment is scaled to 0 and back to 1 before continuing the test.
Also, if the operator pod is removed before the agent CR, the finalizer on the CR cannot be remove any more which blocks the deletion of the entire `instana-agent` namespace in the worst case and locks existing environments in a way that requires manual fixes in the environment. The cleanup logic is adjusted now to remove the finalizer of the agent CR if it is still present before deleting the namespace.
This PR improves robustness of the …
=> ci: Make e2e more robust, force operator redeployment

ci/pipeline.yaml, ci/pr-pipeline.yml, ci/scripts/end-to-end-test.sh
Caching might cause old images to being pulled if branch names are used
=> ci: Rely on commit instead of branch for pulling images

api/v1/inline_types.go, api/v1/inline_types_test.go, ci/scripts/end-to-end-test.sh, pkg/k8s/object/builders/agent/daemonset/daemonset.go, pkg/k8s/object/builders/agent/daemonset/daemonset_test.go, pkg/k8s/object/builders/common/ports/instana_agent_port.go, pkg/k8s/object/builders/common/ports/ports_builder.go, pkg/k8s/object/builders/common/ports/ports_test.go
Card: [INSTA-12524](https://jsw.ibm.com/browse/INSTA-12524)
- Remove obsolete agent-socket port 42666
- Do only bind ports which are enabled on the Daemonset
```
spec:
agent:
configuration_yaml: |
endpointHost: xxx
endpointPort: "443"
env: {}
key: xxx
cluster:
name: konrad
opentelemetry:
grpc:
enabled: false
http:
enabled: true
```
If grpc is enabled, bind 42699 (agent apis) and 55680 (oltp-legacy) and 4317 (otlp-grpc) ports. 
If http is enabled, bind 42699 (agent apis) and 4318 (oltp-http) ports.
By default, bind all ports.
=> Fix: Bind only enabled ports on agent pods

Makefile
Gives us a more accurate output when running tests using `make test` as directory mocks can now be ignored (and any future ignore if necessary)
=> Improve the make test command to ignore mocks dir

config/samples/instana_v1_instanaagent.yaml
When not defined, there is no default value shown on the OCP install page.
=> chore: Add opentelemetry default settings to example

ci/scripts/commit-changes-to-public-repo.sh
The community operator project will reject changes if a leading `v` is part of the folder name
=> ci(fix): Remove leading `v` from OLM package promotion

go.mod
1.23 is not a downloable release. Go mod should list the specific toolchain that can be downloaded as mentioned here: https://github.com/golang/go/issues/62278#issuecomment-1693538776 Otherwise opening the project having a different version installed will result in errors, e.g:
```
$ go version
go: downloading go1.23 (linux/amd64)
go: download go1.23 for linux/amd64: toolchain not available
```
=> go.mod: change version from 1.23 to 1.23.0

api/v1/inline_types.go, ci/scripts/end-to-end-test.sh, config/samples/external_secret_instana_agent_key.yaml, config/samples/instana_v1_extended_instanaagent.yaml, config/samples/instana_v1_instanaagent_multiple_backends.yaml, config/samples/instana_v1_instanaagent_multiple_backends_external_keyssecret.yaml, controllers/apply.go, controllers/instanaagent_controller.go, controllers/util.go, pkg/k8s/object/builders/agent/secrets/config.go, pkg/k8s/object/builders/agent/secrets/config_test.go, pkg/k8s/object/builders/agent/secrets/keys-secret/secret.go, pkg/k8s/object/builders/agent/secrets/keys-secret/secret_test.go, pkg/k8s/object/builders/common/backends/backends.go, pkg/k8s/object/builders/k8s-sensor/configmap/configmap.go, pkg/k8s/object/builders/k8s-sensor/configmap/configmap_test.go, pkg/k8s/object/builders/k8s-sensor/deployment/deployment.go
For each k8sensor backend we get a secret (that stores agent key), configmap (that stores agent endpoint) created and a deployment. Example:
```
✗ k get secrets
NAME                                 TYPE                             DATA   AGE
delivery.instana                     kubernetes.io/dockerconfigjson   1      44h
instana-agent                        Opaque                           1      17h <-- relevant secret
instana-agent-additional-backend-1   Opaque                           1      17h <-- relevant secret
instana-agent-config                 Opaque                           6      17h
```
```
✗ k get cm
NAME                                          DATA   AGE
instana-agent-dependents                      1      17h
instana-agent-k8sensor                        1      17h <-- …
```
=> Add multi-backend k8sensor support

api/v1/inline_types.go, api/v1/inline_types_test.go
The agent should request 768Mi of memory to stay consistent with the current helm chart values.
=> chore: Align agent memory requests with helm chart

ci/pipeline.yaml, ci/pr-pipeline.yml, ci/scripts/reslock.sh
Migrate resource locking to reslock cli to be less CI server dependent.
[INSTA-23500](https://jsw.ibm.com/browse/INSTA-23500)
=> ci: Use reslock for resource locking

pkg/k8s/object/builders/common/volume/volume_builder.go
Mounting the same secret multiple times is valid in Kubernetes, we should not panic here. Example:
```
spec:
agent:
pod:
volumeMounts:
- mountPath: /opt/instana/agent/etc/application.jks
name: jks-mount
subPath: application.jks
- mountPath: /custom-secrets
name: jks-mount
volumes:
- name: jks-mount
secret:
secretName: keystore-secret-name
```
=> fix: Do not panic if number of volumes and mounts do not match

Makefile, bundle/manifests/manager-role_rbac.authorization.k8s.io_v1_role.yaml, config/manager/manager.yaml, config/rbac/role.yaml, config/rbac/role_binding.yaml, e2e/agent_test_api.go, e2e/config.go, e2e/upgrade_test.go, main.go, pkg/k8s/client/client.go
* our operator is named `controller-manager`, and RBAC `manager-role` and `manager-rolebinding` which can conflict with other operators running in the cluster
* use instana-specific resource names
* add logic for cleaning up the old resource on the upgrades
* use the same `LeaderElectionID`
* delete the old deployment if it matches the name and it has the label  `"app.kubernetes.io/name: instana-agent-operator"`
* delete the old manager-role if it matches the name and one of the APIGroups are `instana.io` since we did not set the label on this resource
* delete the old manager-rolebinding if it matches the name and the ServiceAccount
=> [INSTA-24606] Change deployment and rbac naming

ci/pipeline.yaml
* we use resource pipeline-source for running the e2e tests, but we only fetch new code if the `ci/` changes which is problematic
* the code change ensures we always fetch the latest changes of the repository, not just changes coming from the `ci/`
=> Always pick up the latest changes for running e2e tests

config/rbac/role.yaml, controllers/apply.go, controllers/instanaagent_controller.go, pkg/k8s/object/builders/agent/rbac/clusterrole.go, pkg/k8s/object/builders/agent/rbac/clusterrole_test.go, pkg/k8s/object/builders/agent/rbac/clusterrolebinding.go, pkg/k8s/object/builders/agent/rbac/clusterrolebinding_test.go, pkg/k8s/object/builders/agent/rbac/constants.go
These two objects were left missing in the migration of the helm-chart from v1 to v2 and is affecting the correct operation of the prometheus sensor in Kuberentes environments.
In addition, there were a few rbac permissions missing in the `instana-agent-operator` service account, which are needed in the `instana-agent`, and since the `instana-agent-operator` cannot grant permissions to a service account that it tiself does not have, we are adding it there.
=> Add ClusterRole/ClusterRoleBinding to instana-agent service account to enable prometheus sensor in Kubernetes

Makefile
Fixes the following type of error:
````
sh-5.2$ make gen-mocks
go install go.uber.org/mock/mockgen@74a29c6e6c2cbb8ccee94db061c1604ff33fd188
mockgen --source /home/ferenc/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.18.5/pkg/client/interfaces.go --destination ./mocks/k8s_client_mock.go --package mocks
bash: line 1: mockgen: command not found
make: *** [Makefile:265: gen-mocks] Error 127
sh-5.2$
````
=> Fix `mockgen: command not found` when GOBIN is not in PATH

Makefile
Fixes the following type of error:
````
sh-5.2$ make run
go: creating new go.mod: module tmp
Downloading sigs.k8s.io/controller-tools/cmd/controller-gen@v0.14.0
/home/ferenc/github.com/instana/instana-agent-operator/bin/controller-gen object:headerFile="hack/boilerplate.go.txt" paths="./..."
go fmt ./...
go vet ./...
pkg/k8s/client/client_test.go:35:2: no required module provides package github.com/instana/instana-agent-operator/mocks; to add it:
go get github.com/instana/instana-agent-operator/mocks
````
=> Fix missing mocks package when `make run` on a fresh clone

pkg/k8s/object/builders/agent/secrets/config.go, pkg/k8s/object/builders/agent/secrets/config_test.go
When opentelemetry is disabled explicitly, the operator should create a config file to disable the feature on the agent.
=> fix: Adjust logic when to render configuration-opentelemetry.yaml

.github/pull_request_template.md, Dockerfile, Makefile, ci/images/e2e-base-image/Dockerfile, go.mod
New golang was released. I noticed, that this repository did not have any template for creating PRs.
Updated golang to v1.24.0 and added a PR template file.
- [Go changelog](https://tip.golang.org/doc/go1.24)
=> chore(deps): Upgrade golang to v1.24.0, add PR template

pkg/k8s/object/builders/k8s-sensor/deployment/deployment.go
The previous value was 1 second.
And the intention with this change is to optimizing data volume, and also match the Kubernetes UIs granularity, that doesn't go below 10 seconds. Read more in INSTA-17881.
=> [INSTA-17884] feat: Increase default k8sensor pollrate to 10s

config/manager/manager.yaml, e2e/agent_test_api.go, e2e/install_test.go
We want to reduce the footprint of the existing operator deployment and there is no reason to keep multiple instances running any more.
The controller-manager deployment was using 2 instances, but there is actually no need for multiple instances any more, as a failing pod would be restarted and would pick-up differences in the next reconciliation loop.
[Slack discussion](https://instana.slack.com/archives/CHBMGV1FE/p1739782330389249)
=> feat: Scale down controller-mananger to 1 replica

.github/pull_request_template.md, pkg/k8s/object/builders/common/env/env_builder.go, pkg/k8s/object/builders/common/env/env_builder_test.go
In case no credentials were defined, the HTTP proxy settings were rendered broken for the k8sensor. This change fixes this behavior and adds more unit tests.
Add an additional check if credentials are present, remove them if not instead of render empty strings and keep the auth format.
Additionally, other the protocol setting should be translated into the env variable
- INSTA-28191
- TS018624533
=> fix: Handle missing proxy credentials correctly for k8sensor

go.mod
When reading https://github.com/golang/go/issues/62278#issuecomment-1693538776 I noticed that this is only recommended for development versions which are not released yet. This is no longer valid, by default the recommendation is to not use the patch level. If you need to pin to a explicit version, toolchain should be used since 1.21 instead, like `toolchain go1.24.3`. Setting just `go 1.24` will avoid failures if developers do not install the latest patch level yet, but allow the build to pick the most recent patch level.
Go 1.24.3 should be picked up that way on rebuild
Remove patch level from go.mod
- https://github.com/golang/go/issues/62278#issuecomment-1693538776 
Note: Remember to run a [helm chart](https://github.ibm.com/instana/instana-agent-charts) release after the the operator …
=> chore: Do not pin go patch level

e2e/agent_test_api.go
- reverts change from pervious release needed for e2e to pass due to change in env vars ordering
- remove the wait before fetching agent pdos
=> Undo temp e2e change

ci/pipeline.yaml
Currently pipeline fails with 
```
"Validation error: 'github.com/redhat-openshift-ecosystem/openshift-preflight' version '1.13.0' is not supported. Supported versions are: ['1.12.0', '1.12.1'
```
Concourse fetches the latest version that is not supported yet.
=> specify preflight version

Makefile, ci/pipeline.yaml, ci/pr-pipeline.yml, ci/scripts/instana-agent-image-prepuller-ns.yaml, ci/scripts/instana-agent-image-prepuller.yaml
Some clusters have slow network connection and it's hard to write reliable e2e tests if image pulling can take a few seconds to multiple minutes.
`make pre-pull-images` will deploy a new daemonset to pull down images.
- [Story / Card](https://jsw.ibm.com/browse/INSTA-XXXXX)
- [Documentation](http://example.com)
- [CSP](http://example.com)
- [Documentation PR](http://example.com)
=> chore: Add image-pre-pulling to Makefile

Makefile, ci/scripts/setup-ocp-mirror.sh
If network connection is slow or even no public internet connection is available, the ocp internal registry can be leveraged to store images. Using an ImageTagMirrorSet let the cluster pull from the internal registry without changing the image names.
Leverages OCP ImageTagMirrorSet and cluster internal registry to speed up pulls of large images. Purely an internal change for easy setup of test environments, there are no customer facing changes involved.
=> chore: Setup ocp mirror script

Makefile, config/rbac/role.yaml, controllers/instanaagent_controller.go, e2e/agent_test_api.go, e2e/install_test.go, e2e/install_with_pdb_test.go, e2e/multi_backend_test.go, e2e/namespace_configmap_test.go, e2e/upgrade_test.go
When the agent CR contains a podDisruptionBudget setting, the operator fails to reconcile due to missing permissions.
Additionally, the operator must own the resource in order to reconcile e.g. on manual deletions.
Reproducible by defining this setting:
```yaml
...
spec:
k8s_sensor:
podDisruptionBudget:
enabled: true
```
- TS019400543
=> fix: Adjust permissions of operator to control pdb

Makefile, README.md, ci/pipeline.yaml, ci/pr-pipeline.yml
Growing number of tests lead to timeouts in e2e tests in CI from time to time.
Increased timeouts
=> ci: Increase e2e timeouts

ci/scripts/reslock.sh
Forgot to increase the reslock timeout in https://github.com/instana/instana-agent-operator/pull/283
Reslock ensures that we don't use shared resources at the same time between pipelines.
=> ci: Add missing reslock timeout bump

.envrc, .gitignore, README.md, flake.lock, flake.nix
Helps providing a reproducible go development environment in MacOS and Linux, removing some friction with newcomers and easing collaboration.
Added a nix flake that uses the version of go specified in the `go.mod` file so anytime there's an update to the go.mod version then the go version used for development is automatically updated.
In addition make use of direnv to automatically switch to use the devShell from the flake whenever one is inside one of the repository directories.
Added gopls (language server), go-tools (go-imports, godoc, etc..) and operator-sdk to the devShell.
- [Story / Card](https://jsw.ibm.com/browse/INSTA-XXXXX)
- [Documentation](http://example.com)
- [CSP](http://example.com)
- [Documentation PR](http://example.com)
Note: Remember to run a [helm …
=> Add nix flake for reproducible dev environment

pkg/k8s/object/builders/remote-agent/deployment/deployment.go
When the existing remote agent is created without an instana agent, the liveness probe fails as 127.0.0.1:42699 is unreachable. 
As the remote agent does not need to expose ports for use, the liveness probe now execs a command inside the container to check status of the remote agent
- [Story / Card](https://jsw.ibm.com/browse/INSTA-47551)
=> Remote Agent: Update liveness probe logic to prevent restart loop

.githooks/pre-commit, e2e/config.go, e2e/java-demo-app/Dockerfile, e2e/java-demo-app/HelloWorldServer.java, e2e/java-demo-app/README.md, e2e/java-demo-app/deploy.sh, e2e/java-demo-app/deployment.yaml, e2e/selective_monitoring_test.go
Improve test coverage for selective monitoring on a namespace level.
- Add a new test case with a real demo app to ensure we only monitor workload which we should.
- Added a Java demo application in e2e/java-demo-app/ with:
- A simple HTTP server implementation
- Dockerfile for containerization
- Kubernetes deployment manifest
- Implemented a selective monitoring test that:
- Deploys the Java app in three different namespaces with different labels
- Configures the Instana agent with selective monitoring in opt-in mode
- Verifies that only JVMs in opt-in namespaces are monitored
**Note**: Right now there is not a good way to see from the logs if a JVM got ignored correctly. For now the test is deploying all 3 apps at once, checks on which worker nodes they are running and than it checks …
=> e2e: Add selective monitoring test for namespace labels

e2e/selective_monitoring_test.go
The selective monitoring e2e test has been flaky in CI environments, particularly on GKE. The test sometimes fails because it can't find the expected JVM attachment logs within the timeout period, even though the feature is working correctly. This makes our CI pipeline less reliable and can block releases.
- Increased polling interval from 10s to 30s to reduce system load and log volume
- Extended timeout from 5 minutes to 8 minutes to allow more time for test completion
- Improved logging with worker node information for better context
- Added functionality to store agent logs during polling and dump them on test failure
- Enhanced timeout detection and error reporting
- No specific JIRA ticket
=> fix(e2e): improve selective monitoring test reliability in CI

ci/pipeline.yaml
Release pipeline requires update to pass
The release pipeline currently fails with:
```
Error: could not submit to pyxis: could not create test results: status code: 400: body: {"type": "about:blank", "title": "Bad Request", "detail": "Validation error: 'github.com/redhat-openshift-ecosystem/openshift-preflight' version '1.12.1' is not supported. Supported versions are: ['1.13.2', '1.13.3', '1.14.0', '1.14.1']", "status": 400, "trace_id": "0xbd05ab3d6bbc039780bf7757d75047da"}
2025/08/28 14:11:47 could not submit to pyxis: could not create test results: status code: 400: body: {"type": "about:blank", "title": "Bad Request", "detail": "Validation error: 'github.com/redhat-openshift-ecosystem/openshift-preflight' version '1.12.1' is not supported. Supported versions are: ['1.13.2', '1.13.3', …
```
=> ci: Update preflight to supported version

Makefile
The file bundle/manifests/instana-agent-operator.clusterserviceversion.yaml is lacking the relatedImages section otherwise.
Downgraded dependency to last good known version
- https://github.com/redhat-openshift-ecosystem/redhat-marketplace-operators/pull/1132
- https://github.com/redhat-openshift-ecosystem/certified-operators/pull/6520
=> chore(deps): Downgrade operator-sdk to v1.16.0

.pre-commit-config.yaml
There was a known issue in detect-secret where it would run into a dependency issue when running in a newer Python version.
See issue:
https://github.com/IBM/detect-secrets/issues/173
It was fixed in a recent PR: https://github.com/IBM/detect-secrets/pull/174
Update rev of detect-secrets pre-commit hook to fix an issue with the previous version.
- [Story / Card](https://jsw.ibm.com/browse/INSTA-XXXXX)
- [Documentation](http://example.com)
- [CSP](http://example.com)
- [Documentation PR](http://example.com)
=> pre-commit-config: Update detect-secrets to support latest python

ci/pipeline.yaml, ci/scripts/tag-new-release.sh
* fixing pipeline
- [Story / Card](https://jsw.ibm.com/browse/INSTA-XXXXX)
- [Documentation](http://example.com)
- [CSP](http://example.com)
- [Documentation PR](http://example.com)
=> use directory for putting release-version

Makefile
* currently YAML generation includes controller-gen lines, e.g.
```code
Controller-gen binary found in /Users/milica/instana/instana-agent-operator/bin/controller-gen
Updating controller-gen from v0.19.0 to v0.19.0 
Kustomize binary found in /Users/milica/instana/instana-agent-operator/bin/kustomize
Updating kustomize from unknown to v4.5.5 
apiVersion: v1
kind: Namespace
metadata:
labels:
app.kubernetes.io/name: instana-agent-operator
name: instana-agent
```
* added @ prefixes to commands in the controller-yaml and manifests targets to suppress command echoing
* direct outputs to to /dev/null
* direct all echo statements in the controller-gen and kustomize targets to >&2
Note: Remember to run a [helm chart](https://github.ibm.com/instana/instana-agent-charts) release after the the …
=> fix: ensure stdout is not printed in manifest
